### ISSUE TITLE
Add sockets in the client

### ISSUE THREAD

**Issue by Shahar-Y** [meateam/web-ui#148] opened 2020-05-07 07:00 UTC
Create a connection with sockets to socket-service, so the page will reload when on shared folders, and so the envars will update on command.
for more info: 
https://docs.google.com/document/d/1xOXdIX_QrOtFP_n71AotaeqkJ8h2s9457dbmSYpupro/edit

**Comment by yonatandt** [comment] 2020-05-17 07:38
duplicate of #144

**Closed as completed by yonatandt** 2020-05-17 07:38 UTC
